# Generated by Django 4.2.7 on 2023-11-13 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('activity_type', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(max_length=255)),
                ('upload_id', models.BigIntegerField(blank=True, null=True)),
                ('athlete_count', models.IntegerField()),
                ('resource_state', models.IntegerField()),
                ('photo_count', models.IntegerField()),
                ('distance', models.FloatField()),
                ('moving_time', models.IntegerField()),
                ('elapsed_time', models.IntegerField()),
                ('average_speed', models.FloatField()),
                ('max_speed', models.FloatField()),
                ('average_cadence', models.FloatField(blank=True, null=True)),
                ('total_elevation_gain', models.FloatField()),
                ('start_latlng', models.CharField(max_length=255)),
                ('end_latlng', models.CharField(max_length=255)),
                ('calories', models.IntegerField()),
                ('has_heartrate', models.BooleanField(blank=True, null=True)),
                ('achievement_count', models.IntegerField()),
                ('kudos_count', models.IntegerField()),
                ('comment_count', models.IntegerField()),
                ('average_heartrate', models.FloatField(blank=True, null=True)),
                ('average_temp', models.IntegerField(blank=True, null=True)),
                ('has_kudoed', models.BooleanField(default=False)),
                ('max_heartrate', models.FloatField(blank=True, null=True)),
                ('pr_count', models.IntegerField(default=0)),
                ('total_photo_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=255)),
                ('expires_at', models.IntegerField()),
                ('athlete_id', models.IntegerField(unique=True)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Kudoers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kudoer', models.CharField(max_length=255)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Strava_integration.activity')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Strava_integration.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Strava_integration.activity')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Strava_integration.athlete')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='athlete',
            field=models.ForeignKey(db_column='athlete_id', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='Strava_integration.athlete'),
        ),
    ]
