# Generated by Django 2.1 on 2023-10-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strava_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
