# Generated by Django 2.1 on 2023-10-01 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Strava_integration', '0002_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='has_heartrate',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='athlete',
            field=models.ForeignKey(db_column='athlete_id', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='Strava_integration.Athlete'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='sex',
            field=models.CharField(max_length=5),
        ),
    ]
