# Generated by Django 4.2.7 on 2023-11-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strava_integration', '0002_athlete_follower_count_athlete_friend_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='follower_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='friend_count',
            field=models.IntegerField(null=True),
        ),
    ]
