# Generated by Django 2.1 on 2023-10-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strava_integration', '0002_auto_20231014_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='upload_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
