# Generated by Django 4.2.7 on 2023-11-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strava_integration', '0003_alter_athlete_follower_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='follower_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='friend_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
