# Generated by Django 2.1 on 2023-10-15 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Strava_integration', '0004_auto_20231014_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.BigIntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Strava_integration.Athlete')),
            ],
        ),
    ]
