# Generated by Django 4.2.7 on 2023-11-13 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Strava_integration', '0004_alter_athlete_follower_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='friend_count',
            new_name='following_count',
        ),
    ]
