# Generated by Django 2.1 on 2023-10-15 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Strava_integration', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='activity_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Strava_integration.Activity'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
