# Generated by Django 2.1 on 2023-10-19 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Strava_integration', '0006_auto_20231015_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kudoers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kudoer', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Strava_integration.Activity')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Strava_integration.Athlete')),
            ],
        ),
    ]
