# Generated by Django 2.1 on 2023-10-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strava_integration', '0007_kudoers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kudoers',
            name='kudoer',
            field=models.CharField(max_length=255),
        ),
    ]
