# Generated by Django 5.0 on 2023-12-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strava_integration', '0007_alter_activity_calories_alter_activity_end_latlng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='average_watts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='kilojoules',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_watts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='weighted_average_watts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
