# Generated by Django 2.1 on 2023-10-19 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Strava_integration', '0008_auto_20231019_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kudoers',
            name='created_at',
        ),
    ]
